In [1]:
# Let printing work the same in Python 2 and 3
from __future__ import print_function

# NumPy
The NumPy package provides the "ndarray" object. The NumPy array is used to contain data of uniform type with an arbitrary number of dimensions. NumPy then provides basic mathematical and array methods to lay down the foundation for the entire SciPy ecosystem. The following import statement is the generally accepted convention for NumPy.

In [2]:
import numpy as np

## Array Creation
There are several ways to make NumPy arrays. An array has three particular attributes that can be queried: shape, size and the number of dimensions.

In [18]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.size)
print(a.ndim)

(3,)
3
1


In [20]:
x = np.arange(100)
print(x.shape)
print(x.size)
print(x.ndim)
print(x)

(100,)
100
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [22]:
y = np.random.rand(5, 80)
print(y.shape)
print(y.size)
print(y.ndim)
print(y)

(5, 80)
400
2
[[0.62128957 0.39779484 0.91179374 0.88861902 0.14655711 0.26558188
  0.83174738 0.4649444  0.84885888 0.19845605 0.38746793 0.78467514
  0.39915359 0.1265058  0.26121421 0.94298398 0.56378414 0.46174282
  0.9389287  0.23981236 0.7608134  0.28000486 0.46009162 0.60484158
  0.45990542 0.69678155 0.67311921 0.46881365 0.7048507  0.6382802
  0.88122182 0.05786227 0.70050458 0.16159251 0.22477767 0.27845535
  0.53324056 0.29022282 0.29908193 0.50087031 0.47470484 0.55227977
  0.57039127 0.55989139 0.94167243 0.35255874 0.81226349 0.44838036
  0.98437227 0.0754739  0.05860182 0.78970462 0.43412003 0.851923
  0.47556013 0.06481431 0.39834209 0.82739552 0.52714103 0.29674291
  0.90061022 0.70969505 0.3084686  0.03860191 0.18725515 0.39819501
  0.24049931 0.14244038 0.84936371 0.77864083 0.22970633 0.51616099
  0.31449535 0.04270833 0.51082693 0.61539524 0.41227168 0.34525426
  0.93914985 0.7650088 ]
 [0.47879913 0.21359875 0.02411624 0.78733868 0.42981089 0.90798926
  0.4702918 

## Array Manipulation
How to change the shape of an array without a copy!

In [28]:
x.shape = (20, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


NumPy can even automatically figure out the size of at most one dimension for you.

In [29]:
y.shape = (4, 20, -1)
print(y.shape)
print(y)

(4, 20, 5)
[[[0.62128957 0.39779484 0.91179374 0.88861902 0.14655711]
  [0.26558188 0.83174738 0.4649444  0.84885888 0.19845605]
  [0.38746793 0.78467514 0.39915359 0.1265058  0.26121421]
  [0.94298398 0.56378414 0.46174282 0.9389287  0.23981236]
  [0.7608134  0.28000486 0.46009162 0.60484158 0.45990542]
  [0.69678155 0.67311921 0.46881365 0.7048507  0.6382802 ]
  [0.88122182 0.05786227 0.70050458 0.16159251 0.22477767]
  [0.27845535 0.53324056 0.29022282 0.29908193 0.50087031]
  [0.47470484 0.55227977 0.57039127 0.55989139 0.94167243]
  [0.35255874 0.81226349 0.44838036 0.98437227 0.0754739 ]
  [0.05860182 0.78970462 0.43412003 0.851923   0.47556013]
  [0.06481431 0.39834209 0.82739552 0.52714103 0.29674291]
  [0.90061022 0.70969505 0.3084686  0.03860191 0.18725515]
  [0.39819501 0.24049931 0.14244038 0.84936371 0.77864083]
  [0.22970633 0.51616099 0.31449535 0.04270833 0.51082693]
  [0.61539524 0.41227168 0.34525426 0.93914985 0.7650088 ]
  [0.47879913 0.21359875 0.02411624 0.7873386

## Array Indexing

In [30]:
# Scalar Indexing
print(x[2])

[10 11 12 13 14]


In [31]:
# Slicing
print(x[2:5])

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [32]:
# Advanced slicing
print("First 5 rows\n", x[:5])
print("Row 18 to the end\n", x[18:])
print("Last 5 rows\n", x[-5:])
print("Reverse the rows\n", x[::-1])

First 5 rows
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Row 18 to the end
 [[90 91 92 93 94]
 [95 96 97 98 99]]
Last 5 rows
 [[75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
Reverse the rows
 [[95 96 97 98 99]
 [90 91 92 93 94]
 [85 86 87 88 89]
 [80 81 82 83 84]
 [75 76 77 78 79]
 [70 71 72 73 74]
 [65 66 67 68 69]
 [60 61 62 63 64]
 [55 56 57 58 59]
 [50 51 52 53 54]
 [45 46 47 48 49]
 [40 41 42 43 44]
 [35 36 37 38 39]
 [30 31 32 33 34]
 [25 26 27 28 29]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [33]:
# Boolean Indexing
print(x[(x % 2) == 0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [34]:
# Fancy Indexing -- Note the use of a list, not tuple!
print(x[[1, 3, 8, 9, 2]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [10 11 12 13 14]]


## Broadcasting
Broadcasting is a very useful feature of NumPy that will let arrays with differing shapes still be used together. In most cases, broadcasting is faster, and it is more memory efficient than the equivalent full array operation.

In [35]:
print("Shape of X:", x.shape)
print("Shape of Y:", y.shape)

Shape of X: (20, 5)
Shape of Y: (4, 20, 5)


Now, here are three identical assignments. The first one takes full advantage of broadcasting by allowing NumPy to automatically add a new dimension to the *left*. The second explicitly adds that dimension with the special NumPy alias "np.newaxis". These first two creates a singleton dimension without any new arrays being created. That singleton dimension is then implicitly tiled, much like the third example to match with the RHS of the addition operator. However, unlike the third example, the broadcasting merely re-uses the existing data in memory.

In [36]:
a = x + y
print(a.shape)
b = x[np.newaxis, :, :] + y
print(b.shape)
c = np.tile(x, (4, 1, 1)) + y
print(c.shape)
print("Are a and b identical?", np.all(a == b))
print("Are a and c identical?", np.all(a == c))
print(a)

(4, 20, 5)
(4, 20, 5)
(4, 20, 5)
Are a and b identical? True
Are a and c identical? True
[[[ 0.62128957  1.39779484  2.91179374  3.88861902  4.14655711]
  [ 5.26558188  6.83174738  7.4649444   8.84885888  9.19845605]
  [10.38746793 11.78467514 12.39915359 13.1265058  14.26121421]
  [15.94298398 16.56378414 17.46174282 18.9389287  19.23981236]
  [20.7608134  21.28000486 22.46009162 23.60484158 24.45990542]
  [25.69678155 26.67311921 27.46881365 28.7048507  29.6382802 ]
  [30.88122182 31.05786227 32.70050458 33.16159251 34.22477767]
  [35.27845535 36.53324056 37.29022282 38.29908193 39.50087031]
  [40.47470484 41.55227977 42.57039127 43.55989139 44.94167243]
  [45.35255874 46.81226349 47.44838036 48.98437227 49.0754739 ]
  [50.05860182 51.78970462 52.43412003 53.851923   54.47556013]
  [55.06481431 56.39834209 57.82739552 58.52714103 59.29674291]
  [60.90061022 61.70969505 62.3084686  63.03860191 64.18725515]
  [65.39819501 66.24049931 67.14244038 68.84936371 69.77864083]
  [70.22970633 

Another example of broadcasting two 1-D arrays to make a 2-D array.

In [43]:
x = np.arange(-5, 5, 0.1)
y = np.arange(-8, 8, 0.25)
print(x.shape, y.shape)
z = x[np.newaxis, :] * y[:, np.newaxis]
# z = x + y
print(z.shape)
#print(x)

(100,) (64,)
(64, 100)
[-5.00000000e+00 -4.90000000e+00 -4.80000000e+00 -4.70000000e+00
 -4.60000000e+00 -4.50000000e+00 -4.40000000e+00 -4.30000000e+00
 -4.20000000e+00 -4.10000000e+00 -4.00000000e+00 -3.90000000e+00
 -3.80000000e+00 -3.70000000e+00 -3.60000000e+00 -3.50000000e+00
 -3.40000000e+00 -3.30000000e+00 -3.20000000e+00 -3.10000000e+00
 -3.00000000e+00 -2.90000000e+00 -2.80000000e+00 -2.70000000e+00
 -2.60000000e+00 -2.50000000e+00 -2.40000000e+00 -2.30000000e+00
 -2.20000000e+00 -2.10000000e+00 -2.00000000e+00 -1.90000000e+00
 -1.80000000e+00 -1.70000000e+00 -1.60000000e+00 -1.50000000e+00
 -1.40000000e+00 -1.30000000e+00 -1.20000000e+00 -1.10000000e+00
 -1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -1.77635684e-14  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01
  

In [44]:
# More concisely
y, x = np.ogrid[-8:8:0.25, -5:5:0.1]
print(x.shape, y.shape)
z = x * y
print(z.shape)
#print(x)

(1, 100) (64, 1)
(64, 100)
[[-5.  -4.9 -4.8 -4.7 -4.6 -4.5 -4.4 -4.3 -4.2 -4.1 -4.  -3.9 -3.8 -3.7
  -3.6 -3.5 -3.4 -3.3 -3.2 -3.1 -3.  -2.9 -2.8 -2.7 -2.6 -2.5 -2.4 -2.3
  -2.2 -2.1 -2.  -1.9 -1.8 -1.7 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1 -1.  -0.9
  -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5
   0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9
   2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3
   3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7
   4.8  4.9]]
