In [2]:
# Let printing work the same in Python 2 and 3
from __future__ import print_function

# NumPy
The NumPy package provides the "ndarray" object. The NumPy array is used to contain data of uniform type with an arbitrary number of dimensions. NumPy then provides basic mathematical and array methods to lay down the foundation for the entire SciPy ecosystem. The following import statement is the generally accepted convention for NumPy.

In [3]:
import numpy as np

## Array Creation
There are several ways to make NumPy arrays. An array has three particular attributes that can be queried: shape, size and the number of dimensions.

In [8]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.size)
print(a.ndim)
print(a)

(3,)
3
1
[1 2 3]


In [10]:
aa = np.array([1, 2, "pippo"])#questo crea un array "farlocco" di stringhe
print(aa.shape)
print(aa.size)
print(aa.ndim)
print(aa)
aa*a#tento di moltiplicare un array di numeri con uno di stringhe...KO

(3,)
3
1
['1' '2' 'pippo']


TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [12]:
x = np.arange(100)
print(x.shape)
print(x.size)
print(x.ndim)
print(x)

(100,)
100
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [13]:
y = np.random.rand(5, 80)
print(y.shape)
print(y.size)
print(y.ndim)
print(y)

(5, 80)
400
2
[[8.29729742e-01 9.35417743e-01 7.95165497e-01 7.85564497e-02
  8.95203559e-02 6.13752547e-01 4.90600029e-01 6.78275903e-01
  9.52022878e-01 6.81186192e-01 3.89810485e-02 8.35626951e-01
  4.63987037e-02 7.45682876e-01 3.14733421e-01 6.34164295e-01
  5.90965110e-01 1.79705359e-01 7.47892586e-01 2.43806190e-01
  8.53293661e-01 4.83701287e-01 2.38600734e-01 8.09938247e-01
  3.37605811e-01 2.57404614e-01 6.88351099e-01 9.50388895e-01
  9.21063904e-01 3.16498087e-01 5.56132291e-01 4.75261600e-01
  2.70463015e-01 9.98688294e-01 5.74706667e-01 3.22670393e-01
  7.95032845e-01 9.57879958e-01 3.87515742e-01 1.27128068e-01
  5.74704948e-01 3.76446925e-01 5.33041203e-01 8.66060190e-01
  4.93016750e-01 4.11652817e-01 5.63445595e-01 5.13210050e-01
  3.37113744e-01 7.08674618e-01 2.47918150e-01 3.36600662e-01
  2.41787564e-01 8.05573491e-01 1.22792612e-01 5.64461402e-01
  3.44540966e-01 2.81893580e-01 2.53785378e-01 2.53058233e-01
  2.93646245e-02 2.19368342e-01 1.91697220e-01 8.6235021

## Array Manipulation
How to change the shape of an array without a copy!

In [19]:
#occhio che se sbagli, tipo metti x.shape(19,5) non funziona
x.shape = (20, 5)
print(x)
x.shape = (19, 5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


ValueError: cannot reshape array of size 100 into shape (19,5)

NumPy can even automatically figure out the size of at most one dimension for you.

In [15]:
#questo dice a lui di capire se puoi fare tante slice 4 x 20 e sceglie lui come
y.shape = (4, 20, -1)
print(y.shape)
print(y)

(4, 20, 5)
[[[8.29729742e-01 9.35417743e-01 7.95165497e-01 7.85564497e-02
   8.95203559e-02]
  [6.13752547e-01 4.90600029e-01 6.78275903e-01 9.52022878e-01
   6.81186192e-01]
  [3.89810485e-02 8.35626951e-01 4.63987037e-02 7.45682876e-01
   3.14733421e-01]
  [6.34164295e-01 5.90965110e-01 1.79705359e-01 7.47892586e-01
   2.43806190e-01]
  [8.53293661e-01 4.83701287e-01 2.38600734e-01 8.09938247e-01
   3.37605811e-01]
  [2.57404614e-01 6.88351099e-01 9.50388895e-01 9.21063904e-01
   3.16498087e-01]
  [5.56132291e-01 4.75261600e-01 2.70463015e-01 9.98688294e-01
   5.74706667e-01]
  [3.22670393e-01 7.95032845e-01 9.57879958e-01 3.87515742e-01
   1.27128068e-01]
  [5.74704948e-01 3.76446925e-01 5.33041203e-01 8.66060190e-01
   4.93016750e-01]
  [4.11652817e-01 5.63445595e-01 5.13210050e-01 3.37113744e-01
   7.08674618e-01]
  [2.47918150e-01 3.36600662e-01 2.41787564e-01 8.05573491e-01
   1.22792612e-01]
  [5.64461402e-01 3.44540966e-01 2.81893580e-01 2.53785378e-01
   2.53058233e-01]
  [2.

## Array Indexing

In [20]:
# Scalar Indexing
print(x.shape)
print(x[2])

(20, 5)
[10 11 12 13 14]


In [31]:
# Slicing.....RICORDA TUTTO COME IN C++ SI Va DA 0, a N-1 quindi 2:5 significa la riga 2,3,4
print(x[2:5])

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [32]:
# Advanced slicing
print("First 5 rows\n", x[:5])
print("Row 18 to the end\n", x[18:])
print("Last 5 rows\n", x[-5:])
print("Reverse the rows\n", x[::-1])

First 5 rows
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Row 18 to the end
 [[90 91 92 93 94]
 [95 96 97 98 99]]
Last 5 rows
 [[75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
Reverse the rows
 [[95 96 97 98 99]
 [90 91 92 93 94]
 [85 86 87 88 89]
 [80 81 82 83 84]
 [75 76 77 78 79]
 [70 71 72 73 74]
 [65 66 67 68 69]
 [60 61 62 63 64]
 [55 56 57 58 59]
 [50 51 52 53 54]
 [45 46 47 48 49]
 [40 41 42 43 44]
 [35 36 37 38 39]
 [30 31 32 33 34]
 [25 26 27 28 29]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [33]:
# Boolean Indexing
print(x[(x % 2) == 0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [21]:
# Fancy Indexing -- Note the use of a list, not tuple!
print(x[[1, 3, 8, 9, 2]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [10 11 12 13 14]]


## Broadcasting
Broadcasting is a very useful feature of NumPy that will let arrays with differing shapes still be used together. In most cases, broadcasting is faster, and it is more memory efficient than the equivalent full array operation.

In [22]:
print("Shape of X:", x.shape)
print("Shape of Y:", y.shape)

Shape of X: (20, 5)
Shape of Y: (4, 20, 5)


Now, here are three identical assignments. The first one takes full advantage of broadcasting by allowing NumPy to automatically add a new dimension to the *left*. The second explicitly adds that dimension with the special NumPy alias "np.newaxis". These first two creates a singleton dimension without any new arrays being created. That singleton dimension is then implicitly tiled, much like the third example to match with the RHS of the addition operator. However, unlike the third example, the broadcasting merely re-uses the existing data in memory.

In [25]:
#VERO BROADCASTING: NumPy aggiunge in automatico a 'X' una prima dimensione davanti
#NOTA: aggiunge la dimensione mancante sempre a sx
a = x + y  
print(a.shape)

#A MANELLA 01: lo faccio a mano creando un temporaneo che ripete x per 4 slice
b = x[np.newaxis, :, :] + y 
print(b.shape)

#A MANELLA 02:
c = np.tile(x, (4, 1, 1)) + y
print(c.shape)

#Convinciamoci che il Broadcasting funziona
print("Are a and b identical?", np.all(a == b))
print("Are a and c identical?", np.all(a == c))
print(a)

(4, 20, 5)
(4, 20, 5)
(4, 20, 5)
Are a and b identical? True
Are a and c identical? True
[[[ 0.82972974  1.93541774  2.7951655   3.07855645  4.08952036]
  [ 5.61375255  6.49060003  7.6782759   8.95202288  9.68118619]
  [10.03898105 11.83562695 12.0463987  13.74568288 14.31473342]
  [15.6341643  16.59096511 17.17970536 18.74789259 19.24380619]
  [20.85329366 21.48370129 22.23860073 23.80993825 24.33760581]
  [25.25740461 26.6883511  27.9503889  28.9210639  29.31649809]
  [30.55613229 31.4752616  32.27046301 33.99868829 34.57470667]
  [35.32267039 36.79503285 37.95787996 38.38751574 39.12712807]
  [40.57470495 41.37644693 42.5330412  43.86606019 44.49301675]
  [45.41165282 46.56344559 47.51321005 48.33711374 49.70867462]
  [50.24791815 51.33660066 52.24178756 53.80557349 54.12279261]
  [55.5644614  56.34454097 57.28189358 58.25378538 59.25305823]
  [60.02936462 61.21936834 62.19169722 63.86235021 64.3099007 ]
  [65.17229611 66.06195726 67.87770955 68.79397402 69.08133801]
  [70.10326422 

Another example of broadcasting two 1-D arrays to make a 2-D array.

In [31]:
#occhio che qui creo due vettori "riga"
x = np.arange(-5, 5, 0.1)
y = np.arange(-8, 8, 0.25)
print(x.shape, y.shape)
#print(x * y)#da' errore
#print(x + y)#da' errore
z = x[np.newaxis, :] * y[:, np.newaxis]
print(z.shape)

(100,) (64,)
(64, 100)


In [35]:
# More concisely
y, x = np.ogrid[-8:8:0.25, -5:5:0.1]
#nota che mentre sopra la seconda dimensione era "silente" 
#(vedi risultato dello shape) qui è esplicita e l'operazione x*y riesce
#perché creo un vettore "riga" e uno "colonna" 
print(x.shape, y.shape)
z = x * y
print(z.shape)
w = x + y
print(w.shape)

(1, 100) (64, 1)
(64, 100)
(64, 100)
